version: '3.0'
services:
  rasa:
    image: docker.io/miracutor/fushigi-bot-main:0.1
    ports:
      - 5005:5005
  actions:
    image: docker.io/miracutor/fushigi-bot-actions:0.1
    expose:
      - 5055